### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/InheritanceMargin#30]

**Comment by sharwell** [comment]
Blocked on tunnelvisionlabs/vsbase#56.

**Comment by grokky1** [comment]
Is this VS2017 support near completion?

**Comment by xShivan** [comment]
@grokky1 +1 i can't wait too for my favorite extension!

**Comment by xShivan** [comment]
Thanks for merging! So far it's awesome!

**Comment by grokky1** [comment]
👍
