### ISSUE TITLE
Does it work for 3rd party libraries?

### ISSUE THREAD

**Issue by rsheptolut** [tunnelvisionlabs/InheritanceMargin#47]
I usually know all about my code base, but when using other packages from NuGet it is sometimes useful to know which built-in implementations of a certain interface or a base class there are. Is there a way to do this using `InheritanceMargin` in VS2019?

After installing the extension, I started seeing bubbles next to methods and class definitions (took some time to figure out this is what this extension does). But this happens only for "my code". When I need to return an `IActionResult` in `ASP.NET Core` I'm still completely lost about the existing implementations like `FileResult`, etc. ASP.NET core is open source, has great docs and is structured pretty intuitively, but not all packages are like this and there should be an easy way to search for a class that implements a certain interface or inherits a class.

Or maybe `InheritanceMargin` supports this and I'm using it wrong, or it's broken for VS2019?

**Comment by sharwell** [comment]
Navigating to parent types works for external code, but navigating to implementations/derived types only works for code defined in your solution.

**Comment by rsheptolut** [comment]
Thanks @sharwell !
