### ISSUE TITLE
With this extension installed on VS 2015 I often cannot open CS files in the text editor

### ISSUE THREAD

**Issue by joshnorton** [tunnelvisionlabs/InheritanceMargin#6]
If I close and re-open a VS 2015 solution roughly every second time I'm unable to open .cs files in Visual Studio. I'm left with a blank screen that never goes away.

Uninstalling this extension fixes the problem. Re-installing it brings it back. I love this extension so I'd hate to have to leave it uninstalled!

![vs text editor](https://cloud.githubusercontent.com/assets/13478193/8867447/7c52a01e-321d-11e5-9759-bc4599623768.png)

**Comment by joshnorton** [comment]
I just noticed this line in my VS log file, in case it helps to diagnose what's going on:

436
ERROR
Assembly could not be found in MEF cache.
Tvl.VisualStudio.InheritanceMargin.Interfaces, Version=3.0.0.0, Culture=neutral, PublicKeyToken=4c1b7d6d3f8a4723; code-base: file:///C:/USERS/JOSH/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/14.0/EXTENSIONS/UO2MNP0V.BPA/Tvl.VisualStudio.InheritanceMargin.Interfaces.DLL   Microsoft.VisualStudio.CommonIDE.ExtensibilityHosting.VsShellComponentModelHost 2015/07/24 03:32:25.961

**Comment by sharwell** [comment]
I started experiencing this when I updated from 2015 RC to 2015 RTM.

/cc @markw-t @Pilchie This is the same bug we were talking about.

:memo: As best I can tell, recent changes in VS-MEF (internal API) affected the behavior of the `BindingPaths` entry within a **pkgdef** file. It's not the ideal way to register files in Visual Studio 2012+, but this is a Visual Studio 2010+ extension and `ProvideCodeBaseAttribute` is not available (and 2010 doesn't support it at all).

This is a **major** usability nightmare and I need to know whether this is a bug in VS-MEF or a change in behavior that I need to work around in some other way.

**Comment by sharwell** [comment]
Possible solutions include:

1. Use both `[ProvideBindingPath]` and `[ProvideCodeBase]`.
2. Add **Tvl.VisualStudio.InheritanceMargin.Interfaces** to the **source.extension.vsixmanifest** file, even though it doesn't export any MEF objects.

**Comment by joshnorton** [comment]
You mean by adding a MefComponent child element to the Content element? I added <MefComponent>Tvl.VisualStudio.OutputWindow.Interfaces.dll</MefComponent> but it had no effect.

I don't have any experience building VS extensions so please forgive me if I completely missinterpreted your comment.

**Comment by sharwell** [comment]
> You mean by adding a MefComponent child element to the Content element? I added Tvl.VisualStudio.OutputWindow.Interfaces.dll but it had no effect.

Yes. Note that editing the file after the extension is installed probably won't work. You would need to edit it inside the VSIX file and then install it. I'm working on a build for you to test.

**Comment by joshnorton** [comment]
Thanks, a beta build would be great.

**Comment by sharwell** [comment]
@joshnorton It's possible #9 will fix it, and if so then that's the ideal solution (updated Roslyn references for the final release of VS 2015; they needed to be updated anyway). Otherwise, #8 might fix it.

When the AppVeyor build for each of these completes, you'll see a green check mark next to the last commit in the pull request. If you click that check mark, you'll see the CI build results. On of the tabs at the top right says **Artifacts**. The VSIX produced by the build is located there and can be installed for local testing (you'll need to manually uninstall the current extension first if you have it installed).

**Comment by sharwell** [comment]
@joshnorton Sorry I tried and it didn't work. I'll have to look into other ideas tomorrow.

**Comment by joshnorton** [comment]
OK, I'll wait to see what you come up with.

**Comment by sharwell** [comment]
None of my workarounds so far has worked. I'm waiting to hear back from MS about the reason why it's not working (they are busy with an upcoming release and won't be able to get into it for a bit).

**Comment by sharwell** [comment]
I was *so* close in my original guess. In addition to adding the `<MefComponent>` line, the interfaces assembly needed to contain at least one instance of `[Export]`.

**Comment by joshnorton** [comment]
It seems to be working well now. Thanks Sam.

**Comment by voltagex** [comment]
Any updates on this? Is there anything that can be reported to MS via UserVoice or similar?
